[package]
name = "funnybones"
version = "0.1.0"
edition = "2021"

[features]

[[example]]
name = "toy"
required-features = ["cushy"]

[dependencies]
cushy = { git = "https://github.com/khonsulabs/cushy", optional = true }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
